name: CI
on:
  push:
  pull_request:
  schedule:
    - cron: '3 4 * * 5'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
            node-version: '14'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Lint files
        run: npm run lint

  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Récupérer au moins les parents immédiats afin que dans le cas une
          # d'une pull-request, la tête puisse être vérifiée.
          fetch-depth: 2

      # Si cette exécution a été déclenchée par une pull-request : vérifier la
      # la tête (à la place du commit de merge).
      - name: Checkout the head
        run: git checkout HEAD^2
        if: ${{ 'pull_request' == github.event_name }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: 'javascript'

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
            node-version: '14'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Run integration tests
        run: COUNTRY=us npm run test:integration
        if: always()

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js 14
        uses: actions/setup-node@v1
        with:
            node-version: '14'

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Generate coverage report
        run: npm run coverage:lcov
        if: always()

      - name: Send report to Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
        if: always()
